name: Code Scans

on:
  workflow_dispatch: {} # On each manual trigger
  pull_request: {} # Incremental scan of pull request
  push:
    branches: {}
  schedule:
    # do scan at 3:33am every day (UTC+0)
    - cron: '34 2 * * *'

jobs:
  semgrep:
    name: SAST and SCA
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep ci  \
            --sarif  \
            --output results.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Publish SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: Semgrep-Report-${{ github.sha }}
          path: results.sarif
