name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Webhook
        run: |
          curl $WEBHOOK_SECRET
        env:
          WEBHOOK_SECRET: ${{ secrets.RENDER_WEBHOOK_DEPLOY }}
