name: Deploy to Production

on:
  # push on any branch
  push:
    branches:
      - '*'
  # workflow_run:
  #   workflows: ["CI Pipeline"]
  #   types:
  #     - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up bun CLI
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install


      - name: Migrate Database
        run: |
            bunx --bun drizzle-kit generate
            bunx --bun drizzle-kit migrate


      # - name: Trigger Deployment Webhook
      #   run: |
      #     curl $WEBHOOK_SECRET
      #   env:
      #     WEBHOOK_SECRET: ${{ secrets.RENDER_WEBHOOK_DEPLOY }}
