name: pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "export BUN_INSTALL=\$HOME/.bun" >> $GITHUB_ENV
        echo "export PATH=\$BUN_INSTALL/bin:\$PATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        bun install
    - name: Run Pre-Commit Hooks
      run: |
        bunx pre-commit run --all-files
    - name: Run Gitleaks Secret Scan
      run: |
        bunx gitleaks detect --verbose --redact